### ISSUE TITLE
allow bold/italics/links via text "entities"

### ISSUE THREAD

**Issue by Geczy** [alwaysbegrowing/telegram-standup-bot#22]
can only send plaintext

**Comment by RusseII** [comment]
Can you elaborate on the issue here? What happens if I send **hello** (that's telegram bold)

**Comment by Geczy** [comment]
itll send plaintext `hello` (no bold)

there's also another field called `parse_mode` if we want to allow full markdown text (no entities)

![image](https://user-images.githubusercontent.com/1036968/125165618-4de51900-e15d-11eb-8372-4d59c877751c.png)

![image](https://user-images.githubusercontent.com/1036968/125165664-88e74c80-e15d-11eb-8320-5b3c4030a936.png)
