### ISSUE TITLE
WHich bot for Users? 

### ISSUE THREAD

**Issue by RusseII** [alwaysbegrowing/telegram-standup-bot#25]
How do you want to handle which bot we have people use / market? I don't really care - but the main one should be kept up to date with CI 

Also - sad - https://stackoverflow.com/questions/44927298/change-telegram-bot-owner :(

**Comment by RusseII** [comment]
I'd like to get all of our current users and readme messaging clear & on the same bot. Here's the current userlist

Whole family chat
Roos clues chat
Chat with my mom 

I'd like for us to continue to build this out and get others to use the tool as well. I had 10 random groups using the old version before my other telegram account got deleted

**Comment by Geczy** [comment]
What was sad ? I don't care either, we can make an entirely new one if you want

Is this issue just for picking a bot username? In that case may as well keep stood_bot since it's setup on readme

**Comment by RusseII** [comment]
Issue is just in consolidating everything.

Who's DB instance should we use? (we'll both need credentials) 
Who's CRON should we use? (One we can both access, plus future contributors like @SvenWritesCode) 

Webhook url might need updated based on above choices. 

Is there a way we can improve the vercel auto deploys? (we can get a sponsorship from vercel for a free team plan) https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project

**Comment by RusseII** [comment]
https://vercel.com/docs/solutions/cron-jobs 

Thoughts on using github actions for the cron jobs so they are easily viewable and editable by all developers?

**Comment by Geczy** [comment]
Sponsorship is great, can you submit a request for that?

**Comment by Geczy** [comment]
Wow github actions for cron, looks fool proof. I did a quick search for limitations and didn't find any, other than not being able to run shorter than every 5 minutes, which is just fine for us

**Comment by Geczy** [comment]
```name: Scheduler
on:
  schedule:
    - cron: '0 15 * * *'
    - cron: '0 16 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Reminder API
        run: |
          curl --request GET \
          --url 'https://${{ secrets.MAIN_SITE }}/api/reminder?key=${{ secrets.TELEGRAM_API_KEY }}'
```

This is what I have right now for reminder api, but how do we also call send api in the same workflow so that it doesn't run at 15 UTC but rather at 16 UTC? I think need some sort of IF statement , cause if I add it now it'll run both remidner & schedule twice a day

**Comment by Geczy** [comment]
Oh the solution is to create two workflow files, reminder.yml and send.yml

**Comment by RusseII** [comment]
>Sponsorship is great, can you submit a request for that? 
Yes

**Comment by RusseII** [comment]
> Sponsorship is great, can you submit a request for that?

> Yes

Done. @Geczy which database do we want to use? 
Probably yours so please create some DB credentials I can use and send me the env variables (tg api api, db name, botname)

**Comment by RusseII** [comment]
Once you complete that - I'll update the vercel env variables on this repo & fix the failing build. 

Then we can add the github cron tab and only thing left is finishing the vercel sponsorship!

**Comment by Geczy** [comment]
I sent you the env variables so you can setup the github variables with that
