### ISSUE TITLE
UI piece is AWESOME let's make it even better 

### ISSUE THREAD

**Issue by RusseII** [alwaysbegrowing/telegram-standup-bot#26]
Thoughts I had:

- [x] Show most recent unlocked update by default without having to expand the accordion 
- [ ] #49
- [x] What happens after 30 days of updates? The accordions will be miles long 
- [ ] #47

Other notes: 

- [x] There are back-ticks around all of the messages 

![image](https://user-images.githubusercontent.com/15036618/125165628-5c333500-e15d-11eb-957c-b558acf5ad9a.png)

**Comment by Geczy** [comment]
3/5 complete
