### ISSUE TITLE
Enable / disable update lottery system

### ISSUE THREAD

**Issue by Geczy** [alwaysbegrowing/telegram-standup-bot#29]
One person a week per group will get picked to post an update for Friday

```
/enablelottery

/disablelottery
```

Maybe enable / disable command per the group you're in? That way you can pick which groups should get the lottery and which ones get the daily update, rather than an all or nothing setting

**Comment by Geczy** [comment]
Optionally add a UI enhancement to show which groups you're in are part of the lottery

**Comment by SvenWritesCode** [comment]
How is this different than just posting an update on Friday?

**Comment by Geczy** [comment]
One group, perhaps where you work, wants an update every day

Another group, perhaps your friends group, agreed to just do lottery system where only one person is posting an update, which might not necessarily be yourself

**Comment by Geczy** [comment]
This feature should also randomly pick the person in the group. That way the group isn't arguing on who to pick

Have to make sure the picker is "smart"

**Comment by Geczy** [comment]
its 24/7 lottery now
