### ISSUE TITLE
Don’t mention user when posting update

### ISSUE THREAD

**Issue by SvenWritesCode** [alwaysbegrowing/telegram-standup-bot#31]
I do not like being @ mentioned by the bot and do not see a strong reason why I should be alerted to it. I already wrote it. I know about the message.

**Comment by RusseII** [comment]
It was to show which telegram handle the message was from since names are not unique and telegram handles are

**Comment by RusseII** [comment]
I also sometimes click on the mentions to dm the person directly after an update

**Comment by Geczy** [comment]
I think there's a "send silently" option in sendMsg we can use for this

**Comment by RusseII** [comment]
I also personally like it cuz the updates are the section of the telegram messages that I enjoy. When I come back to telegram after a break and click through my mentions it’s nice being able to see all of the updates

**Comment by RusseII** [comment]
Send silently would be cool

**Comment by SvenWritesCode** [comment]
Could we change it to a link to the profile? @RusseII

**Comment by RusseII** [comment]
I’m ultimately fine with just removing it - just wanted to share some use cases

**Comment by SvenWritesCode** [comment]
We could add a notification opt-in for the channel? So even if you don't post an update you can go to that section of chat by the mention.

**Comment by RusseII** [comment]
Personally I’m mostly going to be using the web ui for viewing updates - so for viewing them in tg I’d default to whatever you two prefer

**Comment by Geczy** [comment]
I think you can already go to that section of the chat by mention when its sent silently. The silent option just doesn't ping, but still shows the notification
