### ISSUE TITLE
reactions trigger update

### ISSUE THREAD

**Issue by Namaskar-1F64F** [alwaysbegrowing/telegram-standup-bot#73]
**Describe the bug**
Reactions on old messages re-trigger bot as if they were sent by the author.

**To Reproduce**
1. React to a previous command in the chat
2. Observe stood bot responding to it.

**Expected behavior**
Reactions have no effect on stood bot.

**Screenshots**
![image](https://user-images.githubusercontent.com/7458951/151214567-e4065068-5af0-4ba9-822a-b9bccf1ebf2c.png)
![image](https://user-images.githubusercontent.com/7458951/151214571-5fe240de-dd12-4599-9461-62c4cf0658b8.png)

**Comment by Geczy** [comment]
i wasn't able to reproduce 🤔  am i doing this right? 

![image](https://user-images.githubusercontent.com/1036968/151228877-b331b601-3992-49cc-8735-2016cfccae56.png)

**Comment by Geczy** [comment]
couldnt repro

**Comment by Namaskar-1F64F** [comment]
![Uploading A1C502B6-5408-4299-A6D1-EF53D3E714FF.png…]()

**Comment by Geczy** [comment]
can u reupload @Namaskar-1F64F
